# Generated by Django 4.2.8 on 2024-03-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_review', models.TextField(max_length=500)),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shop.book')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
